In [1]:
import pandas as pd
import os
import csv

In [2]:
final=pd.DataFrame()
files=[file for file in os.listdir('./Input')]
for file in files:
    data=pd.read_excel('./Input/'+file)
    var_Data=[]
    def getdate(data):
        l=data.split(' ')[:3]
        fi=""
        for i in l:
            fi+=i+" "
        return(fi)
    data['Started Time']=data['Started Time'].apply(lambda x: getdate(x))
    data['Started Time']=pd.to_datetime(data["Started Time"],)
    data['Started Time']=data['Started Time'].dt.strftime("%d/%m/%y")
    l=data['Started Time'].unique()
    dates=[]
    for i in l:
        dates.append(i)
        dates.append(i)
        dates.append(i)
        dates.append(i)
    
    dates=sorted(dates)
    
    g=['Mobile Premier League (MPL)','Adda52','Dream 11','Rummy Circle']
    games=[]
    for i in range(len(dates)//4):
        games.append('Mobile Premier League (MPL)')
        games.append('Adda52')
        games.append('Dream 11')
        games.append('Rummy Circle')
        
        
        
    games_selected=[1]*len(dates)
    games_total=[]
    for i in range(0,len(dates),4):
        df=data[data['Started Time'] == dates[i]]
        for j in df[' Which is the first brand that comes to your mind for online ​mobile gaming?']:
            if(j=='Mobile Premier League (MPL)'):
                games_selected[(i)+0]+=1
            if(j=='Adda52'):
                games_selected[(i)+1]+=1
            if(j=='Dream 11'):
                games_selected[(i)+2]+=1
            if(j=='Rummy Circle'):
                games_selected[(i)+3]+=1
        games_total.append(games_selected[(i)+0]+games_selected[(i)+1]+games_selected[(i)+2]+games_selected[(i)+3])
        games_total.append(games_selected[(i)+0]+games_selected[(i)+1]+games_selected[(i)+2]+games_selected[(i)+3])
        games_total.append(games_selected[(i)+0]+games_selected[(i)+1]+games_selected[(i)+2]+games_selected[(i)+3])
        games_total.append(games_selected[(i)+0]+games_selected[(i)+1]+games_selected[(i)+2]+games_selected[(i)+3])
                
                
                
                
    aided_score=[0]*len(dates)
    adided_total=[]
    for i in range(0,len(dates),4):
        df=data[data['Started Time']==dates[i]]
        aided_score[i+0]=df[" Which of the following brands have you heard of?3r - Option 1 "].count()+1
        aided_score[i+1]=df[" Which of the following brands have you heard of?3r - Option 2 "].count()+1
        aided_score[i+2]=df[" Which of the following brands have you heard of?3r - Option 3"].count()+1
        aided_score[i+3]=df[" Which of the following brands have you heard of?3r - Option 4 "].count()+1
        adided_total.append(aided_score[i+0]+aided_score[i+1]+aided_score[i+2]+aided_score[i+3])
        adided_total.append(aided_score[i+0]+aided_score[i+1]+aided_score[i+2]+aided_score[i+3])
        adided_total.append(aided_score[i+0]+aided_score[i+1]+aided_score[i+2]+aided_score[i+3])
        adided_total.append(aided_score[i+0]+aided_score[i+1]+aided_score[i+2]+aided_score[i+3])
        
        
        
    brand_considration=[0]*len(dates)
    brand_total=[]
    for i in range(0,len(dates),4):
        df=data[data['Started Time']==dates[i]]
        brand_considration[i+0]=df[' Which of these brands would you consider for ​skillbased mobile gaming tournaments​? - Mobile Premier League (MPL) '].count()+1
        brand_considration[i+1]=df[' Which of these brands would you consider for ​skillbased mobile gaming tournaments​? - Adda52 '].count()+1
        brand_considration[i+2]=df[' Which of these brands would you consider for ​skillbased mobile gaming tournaments​? - Dream 11 '].count()+1
        brand_considration[i+3]=df[' Which of these brands would you consider for ​skillbased mobile gaming tournaments​? - Rummy Circle '].count()+1
        brand_total.append(brand_considration[i+0]+brand_considration[i+1]+brand_considration[i+2]+brand_considration[i+3])
        brand_total.append(brand_considration[i+0]+brand_considration[i+1]+brand_considration[i+2]+brand_considration[i+3])
        brand_total.append(brand_considration[i+0]+brand_considration[i+1]+brand_considration[i+2]+brand_considration[i+3])
        brand_total.append(brand_considration[i+0]+brand_considration[i+1]+brand_considration[i+2]+brand_considration[i+3])
        
    my_Data={
        'start_date':dates,
        'end_date':dates,
        'Brands':games,
        'Audience':[file.split('.')[0]]*len(dates),
        'unaided_brand_awareness_score':games_selected,
        'aided_brand_awareness_score':aided_score,
        'brand_consideration':brand_considration,
        'game_total':games_total,
        'Aided_total':adided_total,
       'brand_total':brand_total
    }
    score=pd.DataFrame(my_Data)
    if(file.split('.')[0]=='overall'):
        save=score
    else:
        final=pd.concat([final,score])
final=pd.concat([final,save])
final.to_csv('Final.csv')

In [3]:
final['unaided_brand_awareness_score']=(final['unaided_brand_awareness_score']/final['game_total'])
final['unaided_brand_awareness_score']=final['unaided_brand_awareness_score']*10

In [4]:
final['aided_brand_awareness_score']=(final['aided_brand_awareness_score']/final['Aided_total'])
final['aided_brand_awareness_score']=final['aided_brand_awareness_score']*10

In [5]:
final['brand_consideration']=(final['brand_consideration']/final['brand_total'])
final['brand_consideration']=final['brand_consideration']*10

In [6]:
del final['game_total']
del final['Aided_total']
del final['brand_total']

In [7]:
final["overall"]=(final['unaided_brand_awareness_score']+final['aided_brand_awareness_score']+final['brand_consideration'])//3

In [8]:
pd.options.display.float_format = "{:,.2f}".format

In [9]:
final.to_csv('brand_score.csv',   float_format='%.1f',index=False)

In [10]:
final

,start_date,end_date,Brands,Audience,unaided_brand_awareness_score,aided_brand_awareness_score,brand_consideration,overall
0,20/04/20,20/04/20,Mobile Premier League (MPL),Games,3.33,2.86,2.86,3.00
1,20/04/20,20/04/20,Adda52,Games,1.67,4.29,2.86,2.00
2,20/04/20,20/04/20,Dream 11,Games,3.33,1.43,2.86,2.00
3,20/04/20,20/04/20,Rummy Circle,Games,1.67,1.43,1.43,1.00
4,21/04/20,21/04/20,Mobile Premier League (MPL),Games,6.67,6.00,6.67,6.00
...,...,...,...,...,...,...,...,...
35,22/04/20,22/04/20,Rummy Circle,overall,1.67,1.67,1.67,1.00
36,28/04/20,28/04/20,Mobile Premier League (MPL),overall,4.00,2.50,2.50,3.00
37,28/04/20,28/04/20,Adda52,overall,2.00,2.50,2.50,2.00
38,28/04/20,28/04/20,Dream 11,overall,2.00,2.50,2.50,2.00
39,28/04/20,28/04/20,Rummy Circle,overall,2.00,2.50,2.50,2.00

In [16]:
final['Test']=final.groupby('start_date')['overall'].transform(lambda x: sum(l.append(x)))

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [14]:
final

,start_date,end_date,Brands,Audience,unaided_brand_awareness_score,aided_brand_awareness_score,brand_consideration,overall,Test
0,20/04/20,20/04/20,Mobile Premier League (MPL),Games,3.33,2.86,2.86,3.00,33.00
1,20/04/20,20/04/20,Adda52,Games,1.67,4.29,2.86,2.00,33.00
2,20/04/20,20/04/20,Dream 11,Games,3.33,1.43,2.86,2.00,33.00
3,20/04/20,20/04/20,Rummy Circle,Games,1.67,1.43,1.43,1.00,33.00
4,21/04/20,21/04/20,Mobile Premier League (MPL),Games,6.67,6.00,6.67,6.00,30.00
...,...,...,...,...,...,...,...,...,...
35,22/04/20,22/04/20,Rummy Circle,overall,1.67,1.67,1.67,1.00,28.00
36,28/04/20,28/04/20,Mobile Premier League (MPL),overall,4.00,2.50,2.50,3.00,18.00
37,28/04/20,28/04/20,Adda52,overall,2.00,2.50,2.50,2.00,18.00
38,28/04/20,28/04/20,Dream 11,overall,2.00,2.50,2.50,2.00,18.00
39,28/04/20,28/04/20,Rummy Circle,overall,2.00,2.50,2.50,2.00,18.00